Profile scraper
uosoftwareclub/leetcode-scraper pull request #2
Opened 2020-03-22 19:56 UTC by DavidHewWing

2020-03-23 13:33 UTC, wuon approved these changes

2020-03-23 13:58 UTC, l1ghtspeed requested changes

2020-03-23 13:58 UTC, l1ghtspeed commented on src/profile_scraper/user_info.py
> +USERNAMES = [
Since we have atlas set up, we may as well just populate the db and pull data from there

2020-03-23 13:58 UTC, l1ghtspeed commented on src/profile_scraper/scraper.py
> +for username in usernames:
Better to refactor this file into functions for use in the future

2020-03-23 13:58 UTC, l1ghtspeed commented on src/profile_scraper/scraper.py
> +  print((username, ranks_array))
May want to add a task to incorporate slack notifications for success and failures for the lambda scripts

2020-03-23 18:43 UTC, DavidHewWing commented on src/profile_scraper/scraper.py
> +  print((username, ranks_array))
Will do

2020-03-25 02:17 UTC, l1ghtspeed approved these changes

2020-03-25 02:23 UTC, merged